### ISSUE TITLE
Admin tools landing page

### ISSUE THREAD

**Issue by SaschaAdler** [crkn-rcdr/Access-Platform#119]
Some things to make available on the admin tools landing page:

- [ ] The interface that resolves slugs and redirects to the object editor (#96)
- [ ] A link to create a new object (#101)
- [ ] Import from preservation (#100)
- [ ] DMD processing (#113)

We might want to add some additional dashboard-type things to this. (Status of the Hammer and Press queues?)
