### ISSUE TITLE
"Delete Manifest" vs "Unassign Slug"

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#347]
@SaschaAdler would like to simplify `collection` and `manifest` documents to make the `slug` field mandatory.  This is the transparent CRKN assigned identifier, and if we wanted to we can also consider migrating to calling it `CRKNid` or similar in the future.

Deleting a manifest is not simply deleting a single record in CouchDB.  There will also be files in `access-files`  (multi-page PDF) and `access-metadata` (descriptive metadata) Swift containers that will need to be cleaned up.  Files are stored based on the opaque machine assigned identifier (Currently a 'noid', a 'Nice' Opaque IDentifier, but there isn't a technical requirement that this be nice ;-).

**Comment by RussellMcOrmond** [comment]
Additional timing issue.

When a manifest or collection is `unpublished`, there is a process with updateInternalmeta{} which should be allowed to succeed as well before the manifest/collection can be deleted.

**Comment by brittnylapierre** [comment]
> Additional timing issue.
> 
> When a manifest or collection is `unpublished`, there is a process with updateInternalmeta{} which should be allowed to succeed as well before the manifest/collection can be deleted.

Hey @RussellMcOrmond should I check for when requestDate is greater than when the manifest was unpublished and that success is true before allowing for deletion? 

I think I should do this check when the user presses delete, since then I can either display a modal with the deletion warnings, or a modal saying something like "This manifest can't be deleted because background processed are running on it. Please try again later."

Thanks!

**Comment by brittnylapierre** [comment]
### Todos:
- [ ] change  'Unassign Slug' button to say 'Delete'
- [ ] only make delete button visible when unpublished
- [ ] check updateInternalmeta state before allowing deletion

**Comment by RussellMcOrmond** [comment]
When you unpublish, you will be doing a `forceUpdate` which sets that field to only be a date.

If there is an `updateInternalmeta.succeeded` field and it is set to `true`, then you know everything from the unpublish worked well.  You don't need to look at any other parts of the field. Just assume everything else works as expected, as it is a bug in some other code if it is not.


In the future there may be a desire to display errors/warnings for `updateInternalmeta` like is done for other `ProcessUpdate` fields, but that isn't needed for this specific project.  There being a failure that blocks them from deleting a manifest or collection will be so extremely rare that we can do any fix-up manually.  My preference is to not bother displaying/etc those errors, as  replacement metadadatabus functionality that has IIIF inspired schemas for search indexing and presentation documents should come soon, and will have different places to be reporting issues.

**Comment by RussellMcOrmond** [comment]
I should clarify: `updateInternalmeta.succeeded` has 3 possible states:

* Doesn't exist, meaning the processing is in the queue
* is FALSE, meaning something failed in the background that should also disallow deleting until investigated.
* is TRUE, meaning everything worked well and deletion should be allowed.

Given you are displaying a "Please try again later" type message, it may be useful to display a different message on FALSE as "try again later" should become a suggestion they let the platform team know about the error.

When you say "check when the user presses delete", do you mean getting a fresh copy of the document?  This is data that is being updated in the background, and may need to be polled.

**Comment by brittnylapierre** [comment]
Hey Russel! Thank you I just saw this now - Sounds good I can poll for it and display a spinner in the 'please wait' modal so the user doesn't have to manually refresh or remember to come back later.

The background info was very helpful, and I'll add the succeeded = false state too!
