### ISSUE TITLE
Fill in size and MD5 for canvases.

### ISSUE THREAD

**Issue by RussellMcOrmond** [crkn-rcdr/Access-Platform#367]
Creating canvases (with images, etc) is expensive,so should not be tossed away lightly (by a manifest creation process timing out, or the removal of a manifest).

The ability to look up an existing Canvas before potentially creating a new one requires that all canvas records have the size and md5 of the image indexed within CouchDB for quick lookup.   #333

- [x] Add support to CopyCanvas https://github.com/crkn-rcdr/CIHM-Meta/issues/50
- [x] Walk records missing md5 and fill in.
- [x] Add support to Smelter

**Comment by RussellMcOrmond** [comment]
https://admin.canadiana.ca/couchview/canvas/access/missingmastermd5?group=0&range=false&reduce=true

Currently indicates 34055.  Spot checking I found canvases with source paths that no longer exist (SIP update changed pathnames).

Some of these have a `master.extension` field, meaning the image file had been copied.  The next step will be to fill in the md5 from `access-files` if it exists, as well as check if some of these are orphans.

**Comment by RussellMcOrmond** [comment]
With the help of `access-noslug`, `canvas-orphan`, `canvas-set-md5` and `canvas-walk-missingmastermd5` , the older records missing an md5 have been cleaned up. (See: https://github.com/crkn-rcdr/Systems-Administration/tree/main/swift-tools/bin ).

Next step is to add support to Smelter.
